-- -- Widgets table seeds here (Example)
-- INSERT INTO widgets (name, widget_id) VALUES ('Sprockets', 1);
-- INSERT INTO widgets (name, widget_id) VALUES ('Chains', 2);
-- INSERT INTO widgets (name, widget_id) VALUES ('Bearings', 2);
